In [3]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from transformers import BertTokenizer, BertModel

C:\Users\hamza\AppData\Roaming\Python\Python311\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\Users\hamza\AppData\Roaming\Python\Python311\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(


In [33]:
from transformer.Layers import EncoderLayer, DecoderLayer

In [34]:
from transformer.Models import PositionalEncoding

In [5]:
class Encoder(nn.Module):
    def __init__(
            self, bert_model_name, input_embedding_size, d_model, n_layers, n_head, d_k, d_v,
            d_inner, dropout=0.1, max_sequence_length=512):
        super(Encoder, self).__init__()

        # Initialize BERT tokenizer and model
        self.bert_tokenizer = BertTokenizer.from_pretrained(bert_model_name)
        self.bert_model = BertModel.from_pretrained(bert_model_name)

        # Input embedding layer
        self.input_embedding = nn.Linear(self.bert_model.config.hidden_size, input_embedding_size)

        # Positional encoding
        self.positional_encoding = PositionalEncoding(input_embedding_size, max_sequence_length)

        # Multi-layer Transformer encoder
        self.encoder_layers = nn.ModuleList([
            EncoderLayer(d_model, d_inner, n_head, d_k, d_v, dropout=dropout)
            for _ in range(n_layers)
        ])

    def forward(self, input_texts):

        input_ids = self.bert_tokenizer(input_texts, return_tensors='pt', padding=True, truncation=True)['input_ids']
        print(input_ids)
        # BERT tokenization and embedding
        bert_outputs = self.bert_model(input_ids)[0]  # (batch_size, seq_length, hidden_size)

        # Input embedding
        input_embedding = self.input_embedding(bert_outputs)  # (batch_size, seq_length, input_embedding_size)

        # Positional encoding
        positional_encoded_input = self.positional_encoding(input_embedding)  # (batch_size, seq_length, input_embedding_size)

        # Multi-layer Transformer encoder
        encoder_output = positional_encoded_input
        for encoder_layer in self.encoder_layers:
            encoder_output = encoder_layer(encoder_output)  # (batch_size, seq_length, d_model)

        return encoder_output

In [ ]:
bert_outputs = bert_model(input_ids)[0]

In [7]:
import torch
from transformers import BertTokenizer, BertModel
from torch import nn
#from your_module import Encoder  # Import the Encoder class from your module

# Define sample sentence
sample_sentence = "This is a sample sentence."

# Step 1: Tokenize the sample sentence using the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokenized_sentence = tokenizer.encode(sample_sentence, add_special_tokens=True)

# Step 2: Convert tokenized sentence into token IDs
input_ids = torch.tensor([tokenized_sentence])

# Step 3: Prepare input tensor with batch dimension
input_tensor = input_ids  # No need to add batch dimension as input is already batched

# Step 4: Instantiate the Encoder
encoder = Encoder(
    bert_model_name="bert-base-uncased",
    input_embedding_size=512,  # Set input embedding size as per your requirement
    d_model=512,  # Set d_model as per your requirement
    n_layers=6,  # Number of encoder layers
    n_head=8,  # Number of attention heads
    d_k=64,  # Dimensionality of key vectors
    d_v=64,  # Dimensionality of value vectors
    d_inner=2048,  # Dimensionality of inner-layer in feed-forward network
    dropout=0.1,  # Dropout probability
    max_sequence_length=512  # Maximum sequence length
)




tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

AttributeError: 'tuple' object has no attribute 'size'

In [28]:
# Step 4: Instantiate the Encoder
encoder = Encoder(
    bert_model_name="bert-base-uncased",
    input_embedding_size=512,  # Set input embedding size as per your requirement
    d_model=512,  # Set d_model as per your requirement
    n_layers=6,  # Number of encoder layers
    n_head=8,  # Number of attention heads
    d_k=64,  # Dimensionality of key vectors
    d_v=64,  # Dimensionality of value vectors
    d_inner=2048,  # Dimensionality of inner-layer in feed-forward network
    dropout=0.1,  # Dropout probability
    max_sequence_length=512  # Maximum sequence length
)

In [29]:
# Step 5: Pass input tensor through the encoder
encoder_output = encoder("My name is Hamza")

# Step 6: Inspect the encoder output
print("Encoder output shape:", encoder_output.shape)

TypeError: string indices must be integers, not 'tuple'

In [30]:
# Instantiate the encoder
encoder = Encoder(bert_model_name='bert-base-uncased',
                  input_embedding_size=512,
                  d_model=512,
                  n_layers=5,
                  n_head=8,
                  d_k=64,
                  d_v=64,
                  d_inner=2048,
                  dropout=0.1,
                  max_sequence_length=512)



In [31]:

# Define input text
input_text = "my name is hamza"

# Tokenize input text
input_ids = encoder.bert_tokenizer(input_text, return_tensors='pt', padding=True, truncation=True)['input_ids']
input_ids

tensor([[  101,  2026,  2171,  2003, 10654,  4143,   102]])

In [35]:
# Pass through the encoder
encoder_output = encoder.forward(input_text)

# Print output shape
print("Encoder output shape:", encoder_output.shape)

TypeError: string indices must be integers, not 'tuple'

In [21]:
encoder_output = encoder(input_tensor)

AttributeError: 'tuple' object has no attribute 'size'

In [8]:
input_tensor

tensor([[ 101, 2023, 2003, 1037, 7099, 6251, 1012,  102]])

In [ ]:

# Define the Transformer model
class Transformer(nn.Module):
    def __init__(self, encoder, decoder):
        super(Transformer, self).__init__()
        self.encoder = encoder
        self.decoder = decoder

    def forward(self, src_seq, trg_seq):
        enc_output, _ = self.encoder(src_seq)
        dec_output = self.decoder(trg_seq, enc_output)
        return dec_output

# Define the training function
def train_epoch(model, dataloader, optimizer, criterion, device):
    model.train()
    total_loss = 0.0

    for src_seq, trg_seq in dataloader:
        src_seq, trg_seq = src_seq.to(device), trg_seq.to(device)
        
        optimizer.zero_grad()
        output = model(src_seq, trg_seq[:-1])  # Ignore <eos> token in target
        output_dim = output.shape[-1]
        output = output.contiguous().view(-1, output_dim)
        trg_seq = trg_seq[1:].contiguous().view(-1)  # Ignore <sos> token in target

        loss = criterion(output, trg_seq)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(dataloader)

# Example usage
def main():
    # Define your Transformer model
    encoder = Encoder(...)
    decoder = Decoder(...)
    model = Transformer(encoder, decoder)

    # Define your dataloader
    dataloader = DataLoader(...)

    # Define your optimizer and loss function
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    # Train the model
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    num_epochs = 10
    for epoch in range(num_epochs):
        train_loss = train_epoch(model, dataloader, optimizer, criterion, device)
        print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}")

if __name__ == "__main__":
    main()


In [37]:
from transformers import BertModel, BertTokenizer
from torch import nn

# Import transformer encoder layer
from transformers.models.bert.modeling_bert import BertEncoder, BertLayer

# Import positional encoding functions
from torch.nn import TransformerEncoder, TransformerEncoderLayer


In [38]:
# Define input text
input_text = "my name is hamza"

# Tokenize input text
input_ids = BertTokenizer(input_text, return_tensors='pt', padding=True, truncation=True)['input_ids']
input_ids

ValueError: Can't find a vocabulary file at path 'my name is hamza'. To load the vocabulary from a Google pretrained model use `tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`

In [39]:
# Step 1: Tokenize the sample sentence using the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

In [40]:
# Define sample sentence
sample_sentence = "My name is Hamza"

In [41]:
tokenized_sentence = tokenizer.encode(sample_sentence, add_special_tokens=True)

In [42]:





# Step 2: Convert tokenized sentence into token IDs
input_ids = torch.tensor([tokenized_sentence])

# Step 3: Prepare input tensor with batch dimension
input_tensor = input_ids  # No need to add batch dimension as input is already batched

In [44]:
bert_model = BertModel.from_pretrained('bert-base-uncased')

In [45]:
output=bert_model(input_tensor)

In [46]:
output

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.1111,  0.5129, -0.2334,  ..., -0.1131,  0.0528,  0.4727],
         [ 0.0246, -0.1088, -0.6136,  ..., -0.2063, -0.0297,  0.1686],
         [-0.3681,  0.4598,  0.0354,  ..., -0.3725,  0.2379,  0.1640],
         ...,
         [-0.1694,  0.1914, -0.0478,  ..., -0.6429, -0.2118, -0.3504],
         [-0.3843, -0.3724, -0.4704,  ...,  0.5174, -0.0247, -0.5458],
         [ 0.8794,  0.0940, -0.3478,  ...,  0.1397, -0.7686, -0.2198]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-9.0945e-01, -5.6075e-01, -6.4941e-01,  8.0342e-01,  6.8100e-01,
         -1.5603e-01,  8.8296e-01,  4.1021e-01, -5.0835e-01, -9.9997e-01,
         -3.3631e-01,  9.3180e-01,  9.8704e-01,  3.5370e-01,  9.5970e-01,
         -8.0688e-01, -2.7589e-01, -6.7485e-01,  4.2549e-01, -4.5297e-01,
          7.3032e-01,  9.9993e-01,  3.0233e-01,  4.1703e-01,  5.2074e-01,
          9.7937e-01, -7.6852e-01,  9.5116e-01,  9.7300e-01,  7.729

In [47]:
last_hidden_states = output.last_hidden_state
pooled_output = output.pooler_output

In [53]:
input_tensor

tensor([[  101,  2026,  2171,  2003, 10654,  4143,   102]])

In [48]:
last_hidden_states

tensor([[[ 0.1111,  0.5129, -0.2334,  ..., -0.1131,  0.0528,  0.4727],
         [ 0.0246, -0.1088, -0.6136,  ..., -0.2063, -0.0297,  0.1686],
         [-0.3681,  0.4598,  0.0354,  ..., -0.3725,  0.2379,  0.1640],
         ...,
         [-0.1694,  0.1914, -0.0478,  ..., -0.6429, -0.2118, -0.3504],
         [-0.3843, -0.3724, -0.4704,  ...,  0.5174, -0.0247, -0.5458],
         [ 0.8794,  0.0940, -0.3478,  ...,  0.1397, -0.7686, -0.2198]]],
       grad_fn=<NativeLayerNormBackward0>)

In [54]:
output1=bert_model(last_hidden_states[0])


RuntimeError: The expanded size of the tensor (768) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [7, 768].  Tensor sizes: [1, 512]